.TH "Dependency Functions" 3 "16 Oct 2006" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dependency Functions \- Functions to get informations about a libalpm dependency.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBalpm_dep_getinfo\fP (pmdepmissing_t *miss, unsigned char parm)"
.br
.ti -1c
.RI "void * \fBalpm_conflict_getinfo\fP (pmconflict_t *conflict, unsigned char parm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to get informations about a libalpm dependency. 
.PP
.SH "Function Documentation"
.PP 
.SS "void* alpm_conflict_getinfo (pmconflict_t * conflict, unsigned char parm)"
.PP
Get informations about a file conflict. 
.PP
\fBParameters:\fP
.RS 4
\fIconflict\fP database conflict structure 
.br
\fIparm\fP name of the info to get 
.RE
.PP
\fBReturns:\fP
.RS 4
a char* on success (the value), NULL on error 
.RE
.PP

.SS "void* alpm_dep_getinfo (pmdepmissing_t * miss, unsigned char parm)"
.PP
Get informations about a dependency. 
.PP
\fBParameters:\fP
.RS 4
\fImiss\fP dependency pointer 
.br
\fIparm\fP name of the info to get 
.RE
.PP
\fBReturns:\fP
.RS 4
a char* on success (the value), NULL on error 
.RE
.PP

