.TH "Miscellaneous Functions" 3 "16 Oct 2006" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Miscellaneous Functions \- Various libalpm functions.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBalpm_get_md5sum\fP (char *name)"
.br
.ti -1c
.RI "char * \fBalpm_get_sha1sum\fP (char *name)"
.br
.ti -1c
.RI "char * \fBalpm_fetch_pkgurl\fP (char *url)"
.br
.ti -1c
.RI "int \fBalpm_parse_config\fP (char *file, alpm_cb_db_register callback, const char *this_section)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Various libalpm functions. 
.PP
.SH "Function Documentation"
.PP 
.SS "char* alpm_fetch_pkgurl (char * url)"
.PP
Fetch a remote pkg. 
.PP
\fBParameters:\fP
.RS 4
\fIurl\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the downloaded filename on success, NULL on error 
.RE
.PP

.SS "char* alpm_get_md5sum (char * name)"
.PP
Get the md5 sum of file. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP name of the file 
.RE
.PP
\fBReturns:\fP
.RS 4
the checksum on success, NULL on error 
.RE
.PP

.SS "char* alpm_get_sha1sum (char * name)"
.PP
Get the sha1 sum of file. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP name of the file 
.RE
.PP
\fBReturns:\fP
.RS 4
the checksum on success, NULL on error 
.RE
.PP

.SS "int alpm_parse_config (char * file, alpm_cb_db_register callback, const char * this_section)"
.PP
Parses a configuration file. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP path to the config file. 
.br
\fIcallback\fP a function to be called upon new database creation 
.br
\fIthis_section\fP the config current section being parsed 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, -1 on error (pm_errno is set accordingly) 
.RE
.PP

