.TH "Interface Functions" 3 "16 Oct 2006" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface Functions \- Function to initialize and release libalpm.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBalpm_initialize\fP (char *root)"
.br
.ti -1c
.RI "int \fBalpm_release\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function to initialize and release libalpm. 
.PP
.SH "Function Documentation"
.PP 
.SS "int alpm_initialize (char * root)"
.PP
Initializes the library. This must be called before any other functions are called. 
.PP
\fBParameters:\fP
.RS 4
\fIroot\fP the full path of the root we'll be installing to (usually /) 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, -1 on error (pm_errno is set accordingly) 
.RE
.PP

.SS "int alpm_release ()"
.PP
Release the library. This should be the last alpm call you make. 
.PP
\fBReturns:\fP
.RS 4
0 on success, -1 on error (pm_errno is set accordingly) 
.RE
.PP

