.TH "Library Options" 3 "16 Oct 2006" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library Options \- Functions to set and get libalpm options.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBalpm_set_option\fP (unsigned char parm, unsigned long data)"
.br
.ti -1c
.RI "int \fBalpm_get_option\fP (unsigned char parm, long *data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to set and get libalpm options. 
.PP
.SH "Function Documentation"
.PP 
.SS "int alpm_get_option (unsigned char parm, long * data)"
.PP
Get the value of a library option. 
.PP
\fBParameters:\fP
.RS 4
\fIparm\fP the parameter to get 
.br
\fIdata\fP pointer argument to get the value in 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, -1 on error (pm_errno is set accordingly) 
.RE
.PP

.SS "int alpm_set_option (unsigned char parm, unsigned long data)"
.PP
Set a library option. 
.PP
\fBParameters:\fP
.RS 4
\fIparm\fP the name of the parameter 
.br
\fIdata\fP the value of the parameter 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, -1 on error (pm_errno is set accordingly) 
.RE
.PP

