.TH "Sync Functions" 3 "16 Oct 2006" "libalpm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sync Functions \- Functions to get informations about libalpm syncs.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBalpm_sync_getinfo\fP (pmsyncpkg_t *sync, unsigned char parm)"
.br
.ti -1c
.RI "PMList * \fBalpm_db_search\fP (pmdb_t *db)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to get informations about libalpm syncs. 
.PP
.SH "Function Documentation"
.PP 
.SS "PMList* alpm_db_search (pmdb_t * db)"
.PP
Searches a database 
.PP
\fBParameters:\fP
.RS 4
\fIdb\fP pointer to the package database to search in 
.RE
.PP
\fBReturns:\fP
.RS 4
the list of packages on success, NULL on error 
.RE
.PP

.SS "void* alpm_sync_getinfo (pmsyncpkg_t * sync, unsigned char parm)"
.PP
Get informations about a sync. 
.PP
\fBParameters:\fP
.RS 4
\fIsync\fP pointer 
.br
\fIparm\fP name of the info to get 
.RE
.PP
\fBReturns:\fP
.RS 4
a char* on success (the value), NULL on error 
.RE
.PP

