#!/bin/sh
#   pacdiff : a simple pacnew/pacorig/pacsave updater for /etc/
#
#   Copyright (c) 2007 Aaron Griffin <aaronmgriffin@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Original http://phraktured.net/config/bin/pacdiff

diffprog=${DIFFPROG:-vimdiff}
for x in $(find /etc/ -name "*.pacnew" -o -name "*.pacorig" -o -name "*.pacsave")
do
    echo "File: ${x%.pac*}"
    chk="$(cmp $x ${x%.pac*})"
    if [ -z "${chk}" ]; then
        echo "  Files are identical, removing..."
        rm $x
    else
        echo -n "  File differences found. (V)iew, (S)kip, (R)emove: [v/s/r] "
        read c
        c="$(echo $c| tr A-Z a-z)" #tolower
        if [ "$c" = "r" ]; then
            rm $x
        elif [ "$c" = "s" ]; then
            continue
        else
            [ "$c" = "n" -o "$c" = "N" ] || $diffprog $x ${x%.pac*}
            echo -n "  Remove file? [Y/n] "
            read c
            [ "$c" = "n" -o "$c" = "N" ] || rm $x
        fi
    fi
done
