#!/usr/bin/python3

import sys

for path in sys.argv[1:]:
    print('# -----------------------------------')
    print('# ' + path + ':')
    print('# -----------------------------------')
    with open(path, 'r') as f:
        for line in f:
            print('# ' + line, end='')
