.TH libalpm 3 "29 Jan 2006" "Frugalware Developer Manual" ""
.SH NAME
libalpm \- Arch Linux package management library
.SH SYNOPSIS
For ease of access, the libalpm manual has been split up into several sections.

.nf
alpm_databases      Database Functions
alpm_dep            Dependency Functions
alpm_groups         Group Functions
alpm_interface      Interface Functions
alpm_list           List Functions
alpm_log            Logging Functions
alpm_misc           Miscellaneous Functions
alpm_options        Library Options
alpm_packages       Package Functions
alpm_sync           Sync Functions
alpm_trans          Transaction Functions
.fi

.SH AUTHOR
.nf
Judd Vinet <jvinet@zeroflux.org>
and the Frugalware developers <frugalware-devel@frugalware.org>
.fi
