.TH libalpm 3 "07 Jan 2007" "libalpm @PM_VERSION@" ""
.SH NAME
	libalpm \- Arch Linux Package Management library
.SH SYNOPSIS
For ease of access, the libalpm manual has been split up into several sections.

.nf
alpm_databases      Database Functions
alpm_interface      Interface Functions
alpm_list           List Functions
alpm_log            Logging Functions
alpm_misc           Miscellaneous Functions
alpm_packages       Package Functions
alpm_sync           Sync Functions
alpm_trans          Transaction Functions
.fi

.SH AUTHOR
.nf
Judd Vinet <jvinet@zeroflux.org>
.fi
